server:
  port: 8060
#控制session的超时时间，单位：s，默认是30分钟，即30分钟内不做任何操作就会认为超时，然后清除session里的用户信息，最短为1分钟
  servlet:
    session:
      timeout: 600
spring:
  application:
    name: imooc-secutity
  profiles:
    active: dev
imooc:
  security:
    code:
      image:
        length: 2
        width: 600
        url: /authentication/form
      smsCode:
        url: /authentication/mobile
    browser:
      signUpUrl: /demo-signUp.html
#      signOutUrl: /demo-signOut.html
#      loginType: REDIRECT
#      loginPage: /demo-login.html